apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: "development"
  VITE_API_URL: "http://localhost:32001"
  VITE_KEYCLOAK_URL: "http://localhost:32080"
  VITE_KEYCLOAK_REALM: "techzone"
  VITE_KEYCLOAK_CLIENT_ID: "techzone-backend"
