apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mateuszwitkowiak/frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NODE_ENV
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_API_URL
            - name: VITE_KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_KEYCLOAK_URL
            - name: VITE_KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_KEYCLOAK_REALM
