apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGODB_USERNAME: "boskiraptor2"
  MONGODB_PASSWORD: "oFocmXHWMq3zDsjo"
  MONGODB_URI: "mongodb+srv://boskiraptor2:oFocmXHWMq3zDsjo@cluster0.1nr7u.mongodb.net/techzone?retryWrites=true&w=majority&appName=Cluster0"
