apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: mateuszwitkowiak/notification-service:latest
          ports: []
          env:
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: SMTP_PASS
            - name: MAIL_FROM
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: MAIL_FROM
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: RABBITMQ_URL
